version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders-app
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/ordersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Porta padrão para conexões do RabbitMQ
      - "15672:15672" # Porta para acessar o painel de administração
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  database:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ordersdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
